name: build
on: [workflow_dispatch, push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.platform.os }}
          profile: minimal
          override: true
      - name: install Linux dependencies
        if: contains(matrix.platform.target, 'unknown-linux')
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0 libayatana-appindicator3-dev
      - run: npm install
      - run: npm run tauri build
